language: go
go:
  - 1.12.x
  - tip

os:
  - linux
  - osx

sudo: false

install:
  - go get -v ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
    GO111MODULE=on
